# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91441f14ff9fa0d60c058a561c7308c2b050c2cead1c8cc8c6ad95ac8eac38b11a4dce264b7ab3b79d4d129ae9fb8041bd4fcda8d12b4f95bb9ebb568a30a6d7

test:
  secret_key_base: 2e1e853b6cf57878c0edc657e7199b15a916181e914812726975c4b8560232d4e26cc6bed2995d1056b6eac04307b52572ce454cd07b799929cb44c8fd055d38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
